// Code generated by "exemplarpropertizer --interfaceName=FooInterface -t Basicstruct testdata/"; DO NOT EDIT

package main

import "fmt"
import "time"
import "github.com/traitify/common-go/unixtime"

func (this *Basicstruct) ID() int {
	return this.id
}
func (this *Basicstruct) SetID(x int) {
	this.id = x
}
func (this *Basicstruct) Date() time.Time {
	return this.date
}
func (this *Basicstruct) SetDate(x time.Time) {
	this.date = x
}
func (this *Basicstruct) PrevDate() time.Time {
	return this.prevDate
}
func (this *Basicstruct) SetPrevDate(x time.Time) {
	this.prevDate = x
}
func (this *Basicstruct) Status() string {
	return this.status
}
func (this *Basicstruct) SetStatus(x string) {
	this.status = x
}
func (this *Basicstruct) HiddenField() string {
	return this.hiddenField
}
func (this *Basicstruct) SetHiddenField(x string) {
	this.hiddenField = x
}
func (this *Basicstruct) ModifiedAt() unixtime.Millis {
	return this.modifiedAt
}
func (this *Basicstruct) SetModifiedAt(x unixtime.Millis) {
	this.modifiedAt = x
}

type FooInterface interface {
	ID() int
	SetID(x int)
	Date() time.Time
	SetDate(x time.Time)
	PrevDate() time.Time
	SetPrevDate(x time.Time)
	Status() string
	SetStatus(x string)
	HiddenField() string
	SetHiddenField(x string)
	PrivateField() string
	SetPrivateField(x string)
	ModifiedAt() unixtime.Millis
	SetModifiedAt(x unixtime.Millis)
}
